name: Pull Request Security Checks

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    

      # Set up Python environment with version 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install required security scanning tools using pip
      - name: Install dependencies
        run: |
          # Update pip to latest version
          python -m pip install --upgrade pip
          # Install security tools: bandit (SAST), safety (dependency checker), detect-secrets
          pip install bandit safety detect-secrets

      # Run static application security testing (SAST) with Bandit
      - name: SAST Scan with Bandit
        run: |
          # Correcte syntax voor Bandit met severity level
          bandit -r . -v --severity-level low || (
            echo "SAST scan found security issues"
            exit 1
          )
        continue-on-error: true

      # Check for known vulnerabilities in dependencies using Safety
      - name: Check dependencies with Safety
        run: |
            safety check -r requirements.txt --full-report || (echo "Vulnerable dependencies found" && exit 1)

        continue-on-error: true

      # Scan codebase for potential secrets/credentials using detect-secrets
      - name: Check for secrets
        run: |
          # Scan for secrets, filter empty results ('{}'), save to file
          if detect-secrets scan . | grep -v '{}' > secrets.txt; then
            echo "Secrets were detected in the codebase:"
            # Display found secrets
            cat secrets.txt
            exit 1
          fi
