name: Pull Request Security Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety detect-secrets

      - name: SAST Scan with Bandit
        run: |
          bandit -r . -f json -o bandit-results.json
        continue-on-error: true

      - name: Check dependencies with Safety
        run: |
          safety check
        continue-on-error: true

      - name: Check for secrets
        run: |
          detect-secrets scan . > secrets-results.json
        continue-on-error: true

      - name: Evaluate results
        run: |
          if [ -f bandit-results.json ]; then
            if grep -q '"SEVERITY": "HIGH"' bandit-results.json; then
              echo "SAST scan found high severity issues"
              exit 1
            fi
          fi
          
          if [ -f secrets-results.json ]; then
            if [ "$(cat secrets-results.json | grep -v '{}' | wc -l)" -gt 0 ]; then
              echo "Secrets were detected in the codebase"
              exit 1
            fi
          fi