name: Weekly Security Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 on Sunday

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: SAST Scan with Bandit
        run: |
          bandit -r . -f json -o bandit-results.json

      - name: Create Issue on High Severity Findings
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'High Severity Security Issues Found',
              body: 'Weekly security scan has detected high severity issues. Please review the scan results.'
            })